Init database object
EduardvonBriesen/know-your-music pull request #20
Opened 2023-06-29 15:18 UTC by niw5385

- Initial database object is created
- log tracking is established

2023-06-30 14:41 UTC, EduardvonBriesen requested changes
Looks good so far, sorry for being a bit nit-picky :)

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/routes/+layout.svelte
> +	//import {initDataStructure} from "../store/data_structure"
Remove commented out code

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/routes/+layout.svelte
> +
Check that you have eslint setup and format your code when commiting

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/routes/+layout.svelte
> +		setTimeout(authHandler.logout,500);
Is this still needed when getting the `user_id` from the store?

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +import { doc, getDoc,updateDoc,type DocumentData } from "firebase/firestore";
I would move this file into the `lib/firebase` dir

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +        const sessions = history[history.length-1].sessions;
`sessions` is not used

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +export const newHistoryArrayElement = (date: Date )=> {
Function is only used once and only here, it could be removed and shouldn't be exported

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +export const newSessionsArrayElement = (date: Date )=> {
Same thing as with `newHistoryArrayElement`

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +export const initDataStructure = (name: string, email: any )=> {
`email` can be typed as `string` 

Create a Type for the DB object, so we can reuse it in other parts of the code.

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +                outdated: 0,
For better readability, we could go with `"50s", "60s", etc`
```suggestion
                "50s": 0,
                "60s": 0,
```

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +                        correct_one: 0,
Reduce to just `correct` everywhere?
```suggestion
                        correct: 0,
```

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +/* export const getDocRef = async(docName: string, db: any) =>{
Remove commented out code (everywhere)

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/data_structure.ts
> +export const initDataStructure = (name: string, email: any )=> {
This is duplicated

2023-06-30 14:41 UTC, EduardvonBriesen commented on src/store/store.ts
> +		//add logs
Tip: Prefix with `TODO: ` so we can easily find open tasks in our code

2023-06-30 14:47 UTC, EduardvonBriesen commented on src/store/dataBaseLoadings.ts
> +            registered_since: (new Date()).toLocaleDateString(),
There's no need to transform to string, using a Date object gives us better control over how it should be formated in the Frontend

2023-07-01 08:35 UTC, niw5385 commented on src/routes/+layout.svelte
> +
what do you mean?

2023-07-01 08:45 UTC, niw5385 commented on src/routes/+layout.svelte
> +		setTimeout(authHandler.logout,500);
added async attribute to logout function and await before saveHistory -> works now

2023-07-01 08:47 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +import { doc, getDoc,updateDoc,type DocumentData } from "firebase/firestore";
done

2023-07-01 08:49 UTC, EduardvonBriesen commented on src/routes/+layout.svelte
> +
We have a defined set of rules on how our code should be formated (see .prettierrc). You can install the Prettier extension to format your code accordingly

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2023-07-01 08:51 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +        const sessions = history[history.length-1].sessions;
removed

2023-07-01 08:57 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +                        correct_one: 0,
adjusted

2023-07-01 08:58 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +                outdated: 0,
adjusted, we can speak about the exact categories we want to use for the music era in Sundays meeting

2023-07-01 09:00 UTC, niw5385 commented on src/store/store.ts
> +		//add logs
is ackknowledged

2023-07-01 09:00 UTC, niw5385 commented on src/store/data_structure.ts
> +export const initDataStructure = (name: string, email: any )=> {
removed

2023-07-01 09:02 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +            registered_since: (new Date()).toLocaleDateString(),
for "registered since": I can adjust it
for the "date" of a history element : I can't because the Date object includes a time

2023-07-01 09:15 UTC, niw5385 commented on src/routes/+layout.svelte
> +	//import {initDataStructure} from "../store/data_structure"
done

2023-07-01 09:27 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +export const newHistoryArrayElement = (date: Date )=> {
removed

2023-07-01 09:27 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +export const newSessionsArrayElement = (date: Date )=> {
removed

2023-07-01 11:13 UTC, niw5385 commented on src/store/dataBaseLoadings.ts
> +export const initDataStructure = (name: string, email: any )=> {
done

2023-07-01 11:20 UTC, EduardvonBriesen approved these changes

2023-07-01 11:20 UTC, merged