Choosing algorithmus genre levl
EduardvonBriesen/know-your-music pull request #23
Opened 2023-07-02 20:24 UTC by niw5385

mainly two functions added:
(1) getGenreWithLevel -> calculates the genre and the level for the next question, should be called before a new item is generated, the generated item should be of the calculated genre and level
(2) updateUserData -> after the evaluation of a question the user data has to be adjusted by the reached score (0%-100%) of the questions

furthermore:
- data structure for user adjusted two improve the choosing of the next genre/level therefor short term history added

2023-07-03 08:12 UTC, EduardvonBriesen commented on src/lib/firebase/dataBaseLoadings.ts
>              const duration = Math.round(date.valueOf()/1000 ) - begin.seconds;
there is a `getSeconds()` method you can use

2023-07-03 08:30 UTC, EduardvonBriesen requested changes
Looks good so far, most of the comments I left aren't concerning functionality.

I didn't actually test the code.

If you have any sources on the algorithms you used, please add those as a comment in the source code

2023-07-03 08:30 UTC, EduardvonBriesen commented on src/lib/firebase/dataBaseLoadings.ts
>  export type UserData = {
I would move the type definition to a seperat file (e.g. see api type defs)

2023-07-03 08:30 UTC, EduardvonBriesen commented on src/lib/firebase/dataBaseLoadings.ts
> +type LevelData = {
You can use these type definitions in the User Data type

2023-07-03 08:30 UTC, EduardvonBriesen commented on src/lib/firebase/dataBaseLoadings.ts
> + * @returns {Levels}
Method actually returns a string

2023-07-04 05:38 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
>              const duration = Math.round(date.valueOf()/1000 ) - begin.seconds;
I tried it, it isn't working

2023-07-04 05:56 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
>  export type UserData = {
done

2023-07-04 05:58 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
> +type LevelData = {
it is not exactly the same structure

2023-07-04 06:02 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
> + * @returns {Levels}
changed it

2023-07-04 06:16 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
> +const newHistoryArrayElement = (date: Date )=> {
I changed it

2023-07-04 06:20 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
> +    const genreLevelData:LevelData = userData.progress.genres[genre] as LevelData;
I will tried it

2023-07-04 09:48 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
> +export async function updateUserProgressData(db: any, docName: string, relativePoints: number, genre: Genre, level: Levels){
adjusted

2023-07-04 09:48 UTC, niw5385 commented on src/lib/firebase/dataBaseLoadings.ts
> +import { doc, getDoc,updateDoc,type DocumentData} from "firebase/firestore";
done

2023-07-09 10:25 UTC, EduardvonBriesen approved these changes
Made some small adjustments myself, please look over them. Can be merged otherwise

2023-07-09 11:25 UTC, merged