8 design language
EduardvonBriesen/know-your-music pull request #25
Opened 2023-07-09 16:23 UTC by yousri-cherif

2023-07-10 06:40 UTC, EduardvonBriesen requested changes
Great work so far ✨ 

I've left a few comments on things that could be improved (some of which I consider optional).

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/quiz/biography/+page.svelte
> + 	];
Extract this into a utility function, that can be reused in other items

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/quiz/biography/+page.svelte
>  			</section>
Use the following syntax to improve readability (optional)
```suggestion
				class:bg-error-200={!!form && form?.correct}
```

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/quiz/biography/+page.svelte
> +						<button
when using template strings use `` and ${}, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals?retiredLocale=de
```suggestion
							class=`btn w-fit ${form?.correct ? 'variant-filled-success' : 'variant-filled-error'}`
```

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/quiz/discography/+page.svelte
> +
Comments from Biography apply here as well

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/quiz/popularity/+page.svelte
> +	const positiveFeedback = [
Comments from biography apply here as well

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/team/+page.svelte
> +		<p>We are</p>
Since you're reusing this bit, you could try extracting it into its own component (optional)

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/team/+page.svelte
> +</script>
Instead of defining colors here, use the color tokens defined in skeleton (https://www.skeleton.dev/docs/colors) and adjust them through theming.

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/+layout.svelte
>  	<svelte:fragment slot="header">
This can be defined inline with tailwind/skeleton classes, try to avoid writing your own css wherever possible

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/+page.svelte
> +		<div class="words">
There exist grid functionality that auto-layouts based on row width (optional):
https://tailwindcss.com/docs/grid-auto-rows
https://kulturbanause.de/blog/css-grid-auto-fill-responsive-layouts-ohne-media-queries/

2023-07-10 06:40 UTC, EduardvonBriesen commented on src/routes/+layout.svelte
> +		</style>
Remove commented out code

2023-07-11 13:46 UTC, yousri-cherif commented on src/routes/+page.svelte
> +		<div class="words">
Couldn't achieve this using with Tailwind

2023-07-13 13:15 UTC, yousri-cherif commented on src/routes/team/+page.svelte
> +		<p>We are</p>
Done

2023-07-13 13:55 UTC, yousri-cherif commented on src/routes/team/+page.svelte
> +</script>
Done

2023-07-13 15:03 UTC, EduardvonBriesen approved these changes

2023-07-13 15:09 UTC, merged